# Generated by Django 4.2.8 on 2023-12-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workExperience',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='fromDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='toDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='fromDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='toDate',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_projects', to='testapp.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_qualifications', to='testapp.qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workExperience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_work_experience', to='testapp.workexperience'),
        ),
    ]
