# Generated by Django 4.2.8 on 2023-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_workexperience_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workExperience',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='fromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='toDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='fromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='toDate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employee_projects', to='testapp.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(related_name='employee_qualifications', to='testapp.qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workExperience',
            field=models.ManyToManyField(related_name='employee_work_experience', to='testapp.workexperience'),
        ),
    ]
