# Generated by Django 4.2.8 on 2023-12-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_workexperience_address_remove_employee_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workExperience',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.qualification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='workExperience',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.workexperience'),
            preserve_default=False,
        ),
    ]
